// <auto-generated />
using System;
using ExpenseTracker.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117174724_CategoryAndRelations")]
    partial class CategoryAndRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTracker.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RowId")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food & Dining",
                            RowId = "52491cf6-4415-4352-b7f4-503d4738ea52"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transportation",
                            RowId = "43d715ce-f180-4132-a62a-c411cfa33f76"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Groceries",
                            RowId = "6556e545-ce90-4b66-8aed-0be34b7aeb6c"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Utilities",
                            RowId = "0d460124-ddcd-4521-bde7-7e769b220bad"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entertainment",
                            RowId = "57a3b8e7-c89a-4037-a2b7-ae38b9df6654"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Health & Fitness",
                            RowId = "04a486ef-e348-466b-a835-16a504ca7ffd"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Education",
                            RowId = "879dec83-9594-4a8e-ae1f-2fe315aef88f"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Shopping",
                            RowId = "cfa3ee41-41fe-4e6a-8ea3-54ff2db343b7"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rent",
                            RowId = "71948dd0-c32b-44c4-b8df-dc72d7fc824e"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Travel",
                            RowId = "6f1409f3-a93e-4031-bcb1-d3d3c9c1203c"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bills",
                            RowId = "8ce3e2f4-303d-4883-8ab2-9a2112ff3903"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Insurance",
                            RowId = "58b37051-bed9-4cb0-9898-260740a71265"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Miscellaneous",
                            RowId = "c16d5c12-13a9-43fc-b8c7-01425c896e9d"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("RowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RowId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Entities.Expense", b =>
                {
                    b.HasOne("ExpenseTracker.Domain.Entities.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseTracker.Domain.Entities.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Entities.Category", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("ExpenseTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
